server:
  port: 8080

spring:
  application:
    name: assignment

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:musinsa'
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc.core: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

scheduling:
  enable: true
